const linuxCommands = [
    { command: 'ls', description: 'Listar arquivos e diretórios', tags: ['listagem', 'arquivos', 'diretórios'] },
    { command: 'cd', description: 'Mudar de diretório', tags: ['navegação', 'diretórios'] },
    { command: 'pwd', description: 'Mostrar o diretório atual', tags: ['diretório', 'localização'] },
    { command: 'mkdir', description: 'Criar um novo diretório', tags: ['criação', 'diretórios'] },
    { command: 'rmdir', description: 'Remover um diretório vazio', tags: ['remoção', 'diretórios'] },
    { command: 'rm', description: 'Remover arquivos ou diretórios', tags: ['remoção', 'arquivos', 'diretórios'] },
    { command: 'cp', description: 'Copiar arquivos ou diretórios', tags: ['cópia', 'arquivos', 'diretórios'] },
    { command: 'mv', description: 'Mover ou renomear arquivos e diretórios', tags: ['movimentação', 'renomeação', 'arquivos', 'diretórios'] },
    { command: 'touch', description: 'Criar um novo arquivo vazio ou atualizar a data de acesso', tags: ['criação', 'arquivos'] },
    { command: 'cat', description: 'Mostrar o conteúdo de um arquivo', tags: ['visualização', 'arquivos'] },
    { command: 'more', description: 'Visualizar o conteúdo de um arquivo por partes', tags: ['visualização', 'arquivos'] },
    { command: 'less', description: 'Visualizar o conteúdo de um arquivo, com navegação', tags: ['visualização', 'arquivos'] },
    { command: 'head', description: 'Mostrar as primeiras linhas de um arquivo', tags: ['visualização', 'arquivos'] },
    { command: 'tail', description: 'Mostrar as últimas linhas de um arquivo', tags: ['visualização', 'arquivos'] },
    { command: 'grep', description: 'Pesquisar texto em arquivos', tags: ['busca', 'texto', 'arquivos'] },
    { command: 'find', description: 'Buscar arquivos e diretórios', tags: ['busca', 'arquivos', 'diretórios'] },
    { command: 'locate', description: 'Encontrar arquivos rapidamente usando um banco de dados', tags: ['busca', 'arquivos'] },
    { command: 'which', description: 'Mostrar o caminho para um comando', tags: ['localização', 'comandos'] },
    { command: 'man', description: 'Mostrar o manual de um comando', tags: ['ajuda', 'comandos'] },
    { command: 'chmod', description: 'Alterar permissões de arquivos e diretórios', tags: ['permissões', 'arquivos', 'diretórios'] },
    { command: 'chown', description: 'Alterar proprietário e grupo de arquivos e diretórios', tags: ['proprietário', 'grupo', 'arquivos', 'diretórios'] },
    { command: 'ps', description: 'Mostrar processos em execução', tags: ['processos'] },
    { command: 'top', description: 'Mostrar processos em tempo real', tags: ['processos', 'monitoramento'] },
    { command: 'kill', description: 'Enviar um sinal para terminar um processo', tags: ['terminar', 'processos'] },
    { command: 'killall', description: 'Terminar todos os processos com um nome específico', tags: ['terminar', 'processos'] },
    { command: 'df', description: 'Mostrar uso do disco', tags: ['disco', 'espaço'] },
    { command: 'du', description: 'Mostrar uso de espaço em disco por diretório', tags: ['espaço', 'disco', 'diretórios'] },
    { command: 'free', description: 'Mostrar uso de memória', tags: ['memória'] },
    { command: 'top', description: 'Mostrar processos em tempo real', tags: ['processos', 'monitoramento'] },
    { command: 'uname', description: 'Mostrar informações do sistema', tags: ['sistema'] },
    { command: 'uptime', description: 'Mostrar o tempo desde o último boot', tags: ['tempo', 'sistema'] },
    { command: 'date', description: 'Mostrar ou definir a data e hora', tags: ['data', 'hora'] },
    { command: 'cal', description: 'Mostrar um calendário', tags: ['calendário'] },
    { command: 'history', description: 'Mostrar o histórico de comandos', tags: ['histórico', 'comandos'] },
    { command: 'alias', description: 'Criar um atalho para um comando', tags: ['atalhos', 'comandos'] },
    { command: 'nano', description: 'Editor de texto', tags: ['editor', 'texto'] },
    { command: 'vim', description: 'Editor de texto avançado', tags: ['editor', 'texto'] },
    { command: 'sudo', description: 'Executar comandos com privilégios de superusuário', tags: ['privilégios', 'comandos'] },
    { command: 'passwd', description: 'Alterar senha de usuário', tags: ['senha', 'usuário'] },
    { command: 'useradd', description: 'Adicionar um novo usuário', tags: ['usuário', 'adicionar'] },
    { command: 'usermod', description: 'Modificar um usuário existente', tags: ['usuário', 'modificar'] },
    { command: 'userdel', description: 'Excluir um usuário', tags: ['usuário', 'excluir'] },
    { command: 'groupadd', description: 'Adicionar um novo grupo', tags: ['grupo', 'adicionar'] },
    { command: 'groupdel', description: 'Excluir um grupo', tags: ['grupo', 'excluir'] },
    { command: 'groups', description: 'Mostrar os grupos de um usuário', tags: ['usuário', 'grupo'] },
    { command: 'service', description: 'Gerenciar serviços do sistema', tags: ['serviços'] },
    { command: 'systemctl', description: 'Gerenciar serviços e unidades', tags: ['serviços', 'unidades'] },
    { command: 'journalctl', description: 'Mostrar logs do sistema', tags: ['logs', 'sistema'] },
    { command: 'crontab', description: 'Gerenciar tarefas agendadas', tags: ['tarefas', 'agendamento'] },
    { command: 'at', description: 'Agendar a execução de comandos', tags: ['agendamento', 'comandos'] },
    { command: 'wget', description: 'Baixar arquivos da web', tags: ['download', 'web'] },
    { command: 'curl', description: 'Transferir dados de ou para um servidor', tags: ['transferência', 'web'] },
    { command: 'scp', description: 'Copiar arquivos entre hosts na rede', tags: ['cópia', 'rede'] },
    { command: 'rsync', description: 'Sincronizar arquivos e diretórios', tags: ['sincronização', 'arquivos'] },
    { command: 'tar', description: 'Arquivar arquivos', tags: ['arquivos', 'compressão'] },
    { command: 'gzip', description: 'Compactar arquivos', tags: ['compactação', 'arquivos'] },
    { command: 'gunzip', description: 'Descompactar arquivos', tags: ['descompactação', 'arquivos'] },
    { command: 'zip', description: 'Compactar arquivos em um arquivo ZIP', tags: ['compactação', 'arquivos'] },
    { command: 'unzip', description: 'Descompactar arquivos ZIP', tags: ['descompactação', 'arquivos'] },
    { command: 'chmod', description: 'Alterar permissões de arquivos', tags: ['permissões', 'arquivos'] },
    { command: 'chown', description: 'Alterar proprietário e grupo de arquivos', tags: ['proprietário', 'grupo', 'arquivos'] },
    { command: 'df', description: 'Mostrar espaço em disco', tags: ['disco', 'espaço'] },
    { command: 'du', description: 'Mostrar uso de espaço por diretório', tags: ['espaço', 'disco', 'diretórios'] },
    { command: 'find', description: 'Localizar arquivos', tags: ['busca', 'arquivos'] },
    { command: 'locate', description: 'Localizar arquivos rapidamente', tags: ['busca', 'arquivos'] },
    { command: 'updatedb', description: 'Atualizar o banco de dados do locate', tags: ['atualização', 'busca'] },
    { command: 'ps', description: 'Mostrar processos em execução', tags: ['processos'] },
    { command: 'top', description: 'Mostrar processos em tempo real', tags: ['processos', 'monitoramento'] },
    { command: 'htop', description: 'Visualização interativa dos processos', tags: ['processos', 'monitoramento'] },
    { command: 'free', description: 'Mostrar uso de memória', tags: ['memória'] },
    { command: 'uptime', description: 'Mostrar o tempo desde o último boot', tags: ['tempo', 'sistema'] },
    { command: 'date', description: 'Mostrar ou definir data e hora', tags: ['data', 'hora'] },
    { command: 'cal', description: 'Mostrar um calendário', tags: ['calendário'] },
    { command: 'echo', description: 'Exibir uma linha de texto', tags: ['texto', 'exibição'] },
    { command: 'printf', description: 'Formatar e exibir texto', tags: ['texto', 'formatação'] },
    { command: 'bc', description: 'Calculadora de precisão arbitrária', tags: ['calculadora', 'matemática'] },
    { command: 'expr', description: 'Avaliar expressões', tags: ['expressões', 'matemática'] },
    { command: 'diff', description: 'Comparar arquivos linha a linha', tags: ['comparação', 'arquivos'] },
    { command: 'cmp', description: 'Comparar arquivos byte a byte', tags: ['comparação', 'arquivos'] },
    { command: 'sed', description: 'Editor de fluxo de texto', tags: ['texto', 'edição'] },
    { command: 'awk', description: 'Processar e analisar texto', tags: ['texto', 'análise'] },
    { command: 'cut', description: 'Remover seções de cada linha de arquivos', tags: ['texto', 'edição'] },
    { command: 'sort', description: 'Ordenar linhas de texto', tags: ['texto', 'ordenação'] },
    { command: 'uniq', description: 'Remover linhas duplicadas', tags: ['texto', 'filtragem'] },
    { command: 'tee', description: 'Ler da entrada padrão e gravar em arquivos', tags: ['entrada', 'gravação'] },
    { command: 'xargs', description: 'Construir e executar comandos a partir da entrada padrão', tags: ['comandos', 'entrada'] },
    { command: 'script', description: 'Gravar uma sessão de terminal', tags: ['gravação', 'sessão'] },
    { command: 'history', description: 'Mostrar histórico de comandos', tags: ['histórico', 'comandos'] },
    { command: 'alias', description: 'Criar um atalho para um comando', tags: ['atalhos', 'comandos'] },
    { command: 'unalias', description: 'Remover um atalho', tags: ['atalhos', 'comandos'] },
    { command: 'man', description: 'Mostrar o manual de um comando', tags: ['ajuda', 'comandos'] },
    { command: 'info', description: 'Mostrar informações sobre um comando', tags: ['ajuda', 'comandos'] },
    { command: 'help', description: 'Mostrar ajuda sobre comandos', tags: ['ajuda', 'comandos'] },
    { command: 'ssh', description: 'Acessar um servidor remoto', tags: ['acesso', 'rede'] },
    { command: 'scp', description: 'Copiar arquivos entre máquinas via SSH', tags: ['cópia', 'rede'] },
    { command: 'sftp', description: 'Transferir arquivos de forma interativa via SSH', tags: ['transferência', 'rede'] },
    { command: 'rsync', description: 'Sincronizar arquivos entre sistemas', tags: ['sincronização', 'arquivos'] },
    { command: 'wget', description: 'Baixar arquivos da web', tags: ['download', 'web'] },
    { command: 'curl', description: 'Transferir dados para ou de um servidor', tags: ['transferência', 'web'] },
    { command: 'ping', description: 'Verificar a conectividade de rede', tags: ['rede', 'diagnóstico'] },
    { command: 'traceroute', description: 'Rastrear a rota de pacotes de rede', tags: ['rede', 'diagnóstico'] },
    { command: 'netstat', description: 'Mostrar conexões de rede e estatísticas', tags: ['rede', 'estatísticas'] },
    { command: 'ifconfig', description: 'Configurar interfaces de rede', tags: ['rede', 'configuração'] },
    { command: 'ip', description: 'Mostrar e configurar interfaces de rede', tags: ['rede', 'configuração'] },
    { command: 'route', description: 'Mostrar e configurar tabelas de roteamento', tags: ['rede', 'roteamento'] },
    { command: 'hostname', description: 'Mostrar ou definir o nome do host', tags: ['sistema', 'rede'] },
    { command: 'nmcli', description: 'Gerenciar conexões de rede', tags: ['rede', 'configuração'] },
    { command: 'systemctl', description: 'Gerenciar serviços e unidades do sistema', tags: ['serviços', 'sistema'] },
    { command: 'journalctl', description: 'Mostrar logs do sistema', tags: ['logs', 'sistema'] },
    { command: 'crontab', description: 'Gerenciar tarefas agendadas', tags: ['agendamento', 'tarefas'] },
    { command: 'at', description: 'Agendar a execução de comandos', tags: ['agendamento', 'comandos'] },
    { command: 'sleep', description: 'Pausar a execução por um período', tags: ['tempo', 'pausa'] },
    { command: 'shutdown', description: 'Desligar ou reiniciar o sistema', tags: ['sistema', 'desligamento'] },
    { command: 'reboot', description: 'Reiniciar o sistema', tags: ['sistema', 'reinicialização'] },
    { command: 'poweroff', description: 'Desligar o sistema imediatamente', tags: ['sistema', 'desligamento'] },
    { command: 'halt', description: 'Parar todos os processos e desligar o sistema', tags: ['sistema', 'desligamento'] },
    { command: 'service', description: 'Gerenciar serviços do sistema', tags: ['serviços'] },
    { command: 'systemctl', description: 'Gerenciar serviços e unidades', tags: ['serviços', 'unidades'] },
    { command: 'journalctl', description: 'Mostrar logs do sistema', tags: ['logs', 'sistema'] },
    { command: 'lsblk', description: 'Mostrar informações sobre dispositivos de bloco', tags: ['dispositivos', 'armazenamento'] },
    { command: 'blkid', description: 'Mostrar informações sobre dispositivos de bloco', tags: ['dispositivos', 'armazenamento'] },
    { command: 'mount', description: 'Montar sistemas de arquivos', tags: ['armazenamento', 'montagem'] },
    { command: 'umount', description: 'Desmontar sistemas de arquivos', tags: ['armazenamento', 'desmontagem'] },
    { command: 'fsck', description: 'Verificar e reparar sistemas de arquivos', tags: ['armazenamento', 'verificação'] },
    { command: 'dd', description: 'Converter e copiar arquivos', tags: ['cópia', 'arquivos'] },
    { command: 'mkfs', description: 'Criar um sistema de arquivos', tags: ['armazenamento', 'formatação'] },
    { command: 'tune2fs', description: 'Modificar parâmetros de sistema de arquivos ext2/ext3/ext4', tags: ['armazenamento', 'manutenção'] },
    { command: 'e2fsck', description: 'Verificar sistemas de arquivos ext2/ext3/ext4', tags: ['armazenamento', 'verificação'] },
    { command: 'mkswap', description: 'Criar uma área de troca', tags: ['memória', 'swap'] },
    { command: 'swapon', description: 'Ativar uma área de troca', tags: ['memória', 'swap'] },
    { command: 'swapoff', description: 'Desativar uma área de troca', tags: ['memória', 'swap'] },
    { command: 'lsusb', description: 'Mostrar informações sobre dispositivos USB', tags: ['dispositivos', 'USB'] },
    { command: 'lspci', description: 'Mostrar informações sobre dispositivos PCI', tags: ['dispositivos', 'PCI'] },
    { command: 'dmesg', description: 'Mostrar mensagens do buffer do kernel', tags: ['logs', 'sistema'] },
    { command: 'lsmod', description: 'Mostrar módulos do kernel carregados', tags: ['kernel', 'módulos'] },
    { command: 'modprobe', description: 'Adicionar e remover módulos do kernel', tags: ['kernel', 'módulos'] },
    { command: 'insmod', description: 'Inserir um módulo do kernel', tags: ['kernel', 'módulos'] },
    { command: 'rmmod', description: 'Remover um módulo do kernel', tags: ['kernel', 'módulos'] },
    { command: 'depmod', description: 'Gerar dependências de módulos do kernel', tags: ['kernel', 'módulos'] },
    { command: 'uname', description: 'Mostrar informações do sistema', tags: ['sistema'] },
    { command: 'hostname', description: 'Mostrar ou definir o nome do host', tags: ['sistema', 'rede'] },
    { command: 'uptime', description: 'Mostrar o tempo desde o último boot', tags: ['sistema', 'tempo'] },
    { command: 'dmesg', description: 'Mostrar mensagens do kernel', tags: ['sistema', 'logs'] },
    { command: 'lsmod', description: 'Listar módulos do kernel carregados', tags: ['sistema', 'kernel'] },
    { command: 'modinfo', description: 'Mostrar informações sobre um módulo do kernel', tags: ['sistema', 'kernel'] }
  ];
  
  export default linuxCommands;
  